### ISSUE TITLE
UST events don't appear in events table, in Experiment, when Trace Compass running on Windows

### ISSUE THREAD

**Issue by DavidA2014** [eclipse-tracecompass/org.eclipse.tracecompass#90] opened 2024-05-23 15:11 UTC
I followed video [(17) Viewing an LTTng and UST trace simultaneously in Eclipse Trace Compass - YouTube](https://www.youtube.com/watch?v=xx1IpKXuMGA).

With Trace Compass running in WSL I could view UST and kernel events in both the LTTng resources view and the Events table, as demo'd in the video.

However, with Trace Compass 9.3.0 running in Windows 11, I observed:
- UST and kernel events both appeared in the LTTng resources view
- Only kernel events appeared in the Events table.

This appears to be a bug?

**Comment by MatthewKhouzam** [comment] 2024-05-23 20:55
If this is true, it is a bug. I will ask our devs on windows to look into it!

**Comment by vladarama** [comment] 2024-05-24 12:59
I tried replicating the bug using Trace Compass 9.3.0 running on Windows 11 using some test traces and everything seems to be working as expected. Both kernel and ust traces appear in the events table and in the resources view.

![image](https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/assets/86936229/7f56f831-546e-46c8-86ef-e4383fc6d330)

**Comment by MatthewKhouzam** [comment] 2024-05-24 14:19
Hi David, now that we know the UST works in the events table, could you confirm that searching on the trace for UST returns empty in the events table?

**Comment by MatthewKhouzam** [comment] 2024-05-24 14:53
Very interesting. Can you doubleclick on the loop exception and share the stack?

**Comment by DavidA2014** [comment] 2024-05-24 15:04
java.lang.NoSuchMethodError: 'org.eclipse.tracecompass.analysis.profiling.core.model.IHostModel org.eclipse.tracecompass.internal.analysis.profiling.core.model.ModelManager.getModelFor(java.lang.String)'
	at org.eclipse.tracecompass.incubator.analysis.core.aspects.AnalysisTidAspect.resolve(AnalysisTidAspect.java:55)
	at org.eclipse.tracecompass.analysis.os.linux.core.event.aspect.LinuxTidAspect.resolve(LinuxTidAspect.java:1)
	at org.eclipse.tracecompass.tmf.core.trace.TmfTraceUtils.resolveIntEventAspectOfClassForEvent(TmfTraceUtils.java:273)
	at org.eclipse.tracecompass.internal.analysis.os.linux.core.kernel.KernelPidAspect.resolve(KernelPidAspect.java:59)
	at org.eclipse.tracecompass.internal.analysis.os.linux.core.kernel.KernelPidAspect.resolve(KernelPidAspect.java:48)
	at org.eclipse.tracecompass.analysis.os.linux.core.event.aspect.LinuxPidAspect.resolve(LinuxPidAspect.java:1)
	at org.eclipse.tracecompass.tmf.ui.viewers.events.columns.TmfEventTableColumn.getItemString(TmfEventTableColumn.java:111)
	at org.eclipse.tracecompass.tmf.ui.viewers.events.TmfEventsTable.getItemStrings(TmfEventsTable.java:2752)
	at org.eclipse.tracecompass.tmf.ui.viewers.events.TmfEventsTable.setItemData(TmfEventsTable.java:1541)
	at org.eclipse.tracecompass.tmf.ui.viewers.events.TmfEventsTable$SetDataListener.handleEvent(TmfEventsTable.java:435)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.tracecompass.tmf.ui.widgets.virtualtable.TmfVirtualTable.setDataItem(TmfVirtualTable.java:571)
	at org.eclipse.tracecompass.tmf.ui.widgets.virtualtable.TmfVirtualTable.refreshTable(TmfVirtualTable.java:1056)
	at org.eclipse.tracecompass.tmf.ui.widgets.virtualtable.TmfVirtualTable.refresh(TmfVirtualTable.java:1009)
	at org.eclipse.tracecompass.tmf.ui.viewers.events.TmfEventsTable$FilterThread.lambda$0(TmfEventsTable.java:2272)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.tracecompass.internal.tracing.rcp.ui.Application.start(Application.java:95)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

**Comment by bhufmann** [comment] 2024-05-24 16:34
I think if you use the Trace Compass RCP release 9.3.0 and install incubator features from https://download.eclipse.org/tracecompass.incubator/master/repository/, then this is error happens, because the update site is not compatible with the 9.3.0 release. Some features were moved from incubator to Trace Compass mainline (incubator callstack) and the 9.3.0 release doesn't have the migrated code. I can reproduce that behaviour on my laptop and it's also happening on Linux and not just Windows.

You will have to use install the incubator features using the `Add-ons` menu or using update site https://download.eclipse.org/tracecompass.incubator/stable-9.3/repository/. 

Unfortunately, that update site is currently broken. I'm working on a fix for that with PR: https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/29. Once it's merged I can re-build the stable-9.3 updates side.

After that I suggest that you install the incubator features from the `Add-on` menu or from that update-site. (BTW, the `Add-on` uses that update site). You might want to start from a freshly extracted Trace Compass 9.3. RCP zip file.

**Comment by MatthewKhouzam** [comment] 2024-05-24 20:21
I will close this now then. Thanks for bringing this up, now the search engines will know!

**Closed by MatthewKhouzam** 2024-05-24 20:21 UTC
